In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("/content/zara.csv", sep = ';')

In [6]:
df.head()

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19T08:50:08.453847,jackets,MAN

In [8]:
df.isnull().sum()

Product ID          0
Product Position    0
Promotion           0
Product Category    0
Seasonal            0
Sales Volume        0
brand               0
url                 0
sku                 0
name                1
description         2
price               0
currency            0
scraped_at          0
terms               0
section             0
dtype: int64

In [9]:
df.dtypes

Product ID            int64
Product Position     object
Promotion            object
Product Category     object
Seasonal             object
Sales Volume          int64
brand                object
url                  object
sku                  object
name                 object
description          object
price               float64
currency             object
scraped_at           object
terms                object
section              object
dtype: object

In [10]:
df.columns

Index(['Product ID', 'Product Position', 'Promotion', 'Product Category',
       'Seasonal', 'Sales Volume', 'brand', 'url', 'sku', 'name',
       'description', 'price', 'currency', 'scraped_at', 'terms', 'section'],
      dtype='object')

In [11]:
df.drop(['Product Category','brand', 'url','sku', 'description', 'currency', 'scraped_at'],axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product ID        252 non-null    int64
 1   Product Position  252 non-null    object
 2   Promotion         252 non-null    object
 3   Seasonal          252 non-null    object
 4   Sales Volume      252 non-null    int64
 5   name              251 non-null    object
 6   price             252 non-null    float64
 7   terms             252 non-null    object
 8   section           252 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 17.8+ KB

In [12]:
df["Total"] = df["price"] * df["Sales Volume"]
df.head()

,Product ID,Product Position,Promotion,Seasonal,Sales Volume,name,price,terms,section,Total
0,185102,Aisle,No,No,2823,BASIC PUFFER JACKET,19.99,jackets,MAN,56431.77
1,188771,Aisle,No,No,654,TUXEDO JACKET,169.00,jackets,MAN,110526.00
2,180176,End-cap,Yes,Yes,2220,SLIM FIT SUIT JACKET,129.00,jackets,MAN,286380.00
3,112917,Aisle,Yes,Yes,1568,STRETCH SUIT JACKET,129.00,jackets,MAN,202272.00
4,192936,End-cap,No,Yes,2942,DOUBLE FACED JACKET,139.00,jackets,MAN,408938.00

In [13]:
df.loc[ df["section"] == "WOMAN", "section"] = "Woman"
df.loc[ df["section"] == "MAN", "section"] = "Man"

In [14]:
df.head()

,Product ID,Product Position,Promotion,Seasonal,Sales Volume,name,price,terms,section,Total
0,185102,Aisle,No,No,2823,BASIC PUFFER JACKET,19.99,jackets,Man,56431.77
1,188771,Aisle,No,No,654,TUXEDO JACKET,169.00,jackets,Man,110526.00
2,180176,End-cap,Yes,Yes,2220,SLIM FIT SUIT JACKET,129.00,jackets,Man,286380.00
3,112917,Aisle,Yes,Yes,1568,STRETCH SUIT JACKET,129.00,jackets,Man,202272.00
4,192936,End-cap,No,Yes,2942,DOUBLE FACED JACKET,139.00,jackets,Man,408938.00

In [16]:
df.nunique()

Product ID          252
Product Position      3
Promotion             2
Seasonal              2
Sales Volume        234
name                194
price                28
terms                 5
section               2
Total               250
dtype: int64

In [17]:
df.shape

(252, 10)

In [22]:
df['Product Position'].unique()

array(['Aisle', 'End-cap', 'Front of Store'], dtype=object)

In [23]:
df['Promotion'].unique()

array(['No', 'Yes'], dtype=object)

In [24]:
df['Seasonal'].unique()

array(['No', 'Yes'], dtype=object)

In [25]:
df['terms'].unique()

array(['jackets', 'shoes', 'sweaters', 'jeans', 't-shirts'], dtype=object)

In [26]:
df['section'].unique()

array(['Man', 'Woman'], dtype=object)

In [27]:
df.isnull().sum()

Product ID          0
Product Position    0
Promotion           0
Seasonal            0
Sales Volume        0
name                1
price               0
terms               0
section             0
Total               0
dtype: int64

In [28]:
df.dropna(inplace=True)

In [29]:
df.isnull().sum()

Product ID          0
Product Position    0
Promotion           0
Seasonal            0
Sales Volume        0
name                0
price               0
terms               0
section             0
Total               0
dtype: int64

In [30]:
df.shape

(251, 10)

In [31]:
from google.colab import files
df.to_csv('downloaded_dataframe.csv', encoding = 'utf-8-sig')
files.download('downloaded_dataframe.csv')